spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - com.white.robot.plugin.LogPlugin # 日志插件
      - com.white.robot.plugin.DemoPlugin # 测试插件
      - com.white.robot.plugin.HelloPlugin # 测试插件

server:
  port: 8081